name: pop-ex
channels:
  - default
dependencies:
  - python=3.8.10
  - ipython
  - ipykernel
  - jupyterlab
  - pip
  - pip:
    - numpy
    - git+git://github.com/randlab/geone@bd67d3f#egg=geone
    - pyvista
    - popex==1.4.0
    - flopy
    - joblib
    - pandas

